@startuml

package "get Papers" {
[search_paper]
[get_semanticscolar]
[get_arXiv]
}

package "External APIs" {
  (Semantic Scholar API)
  (arXiv API)
  (groq API)
}

database "sqLite Database" as db

[make_query] --> [print_query]
[make_query] --> [search_paper]
[make_query] <--> (groq API)

[search_paper] --> [extract_text_from_url] 
[search_paper] <--> [get_semanticscolar] 
[search_paper] <--> [get_arXiv]
[search_paper] --> db

[get_semanticscolar] <--> (Semantic Scholar API)
[get_arXiv] <--> (arXiv API)


[search_paper] --> [print_paper_list]
[print_paper_list] <-- db


[extract_text_from_url] --> [analyze_paper_content]
[analyze_paper_content] --> [print_top_match]
[analyze_paper_content] <--> (groq API)
[analyze_paper_content] <--> db

[print_paper_list] --> client_output
[print_query] --> client_output
[print_top_match] --> client_output
@enduml
